Recipes/config/routes.rb
Rails.application.routes.draw do
  get 'recipe3/recipe3'
  get 'recipe2/recipe2'
  get 'recipe/recipe1'
  get 'welcome/index'
  
  resources :articles do
    resources :comments
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Recipes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Recipes/app/models/article.rb
class Article < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :Recipe_Name, presence: true, length: {minimum: 3}
    validates :Ingredients_and_Supplies, presence: true, length: {minimum: 10}
    validates :Directions, presence: true, length: {minimum: 15}
end

Recipes/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

Recipes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Recipes/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
    end
    
    def new
        @article = Article.new
    end
    
    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render 'new'
        end
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end
end

private
    def article_params
        params.require(:article).permit(:Recipe_Name, :Ingredients_and_Supplies, :Directions)
    end

Recipes/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end
    
    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
    end
    
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

Recipes/app/controllers/recipe2_controller.rb
class Recipe2Controller < ApplicationController
  def recipe2
  end
end

Recipes/app/controllers/recipe3_controller.rb
class Recipe3Controller < ApplicationController
  def recipe3
  end
end

Recipes/app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
  def recipe1
  end
end

Recipes/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Recipes/app/helpers/application_helper.rb
module ApplicationHelper
end

Recipes/app/helpers/articles_helper.rb
module ArticlesHelper
end

Recipes/app/helpers/comments_helper.rb
module CommentsHelper
end

Recipes/app/helpers/recipe2_helper.rb
module Recipe2Helper
end

Recipes/app/helpers/recipe3_helper.rb
module Recipe3Helper
end

Recipes/app/helpers/recipe_helper.rb
module RecipeHelper
end

Recipes/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Recipes/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :Recipe_Name %><br>
    <%= f.text_field :Recipe_Name %>
  </p>
 
  <p>
    <%= f.label :Ingredients_and_Supplies %><br>
    <%= f.text_area :Ingredients_and_Supplies %>
  </p>
 
  <p>
    <%= f.label :Directions %><br>
    <%= f.text_area :Directions %>
  </p>
 
  <p>
    <%= f.submit :Save %>
  </p>
 
<% end %>

Recipes/app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

Recipes/app/views/articles/index.html.erb
<h1>Listing Recipes</h1>

<table>
  <tr>
    <th>Recipe Name</th>
  </tr>
  
  <tr>
    <td><font color="#59f75f">Shepards Pie</font></td>
    <td><%= link_to 'Show', recipe_recipe1_path %></td>
  <tr>
      
  <tr>
    <td><font color="#59f75f">Pecan Pie</font></td>
    <td><%= link_to 'Show', recipe2_recipe2_path %></td>
  <tr>
      
  <tr>
    <td><font color="#59f75f">Blueberry Scones with Lemon Glaze</font></td>
    <td><%= link_to 'Show', recipe3_recipe3_path %></td>
  <tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><font color="#59f75f"><%= article.Recipe_Name %></font></td>
      
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy',
                                article_path(article),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

</br>
</br>
<%= link_to 'Back to Main Page', welcome_index_path %>
</br>
<%= link_to 'New Recipe', new_article_path %>

Recipes/app/views/articles/new.html.erb
<h1>New Recipe</h1>

<%= render 'form' %>

<%= link_to 'Back to Main Page', welcome_index_path %>
</br>
<%= link_to 'Back to Recipe Book', articles_path %>

Recipes/app/views/articles/show.html.erb
<p>
    <h2>Recipe Name:</h2>
    </br>
    <text><%=@article.Recipe_Name %></text>
</p>

<p>
    <h2>Ingredients and Supplies:</h2>
    </br>
    <text><%=@article.Ingredients_and_Supplies %></text>
   
</p>

<p>
    <h2>Directions:</h2>
    </br>
    <text><%=@article.Directions %></text>

</p>

<h2>Comments</h2>
<%= render @article.comments %>
</br>
</br>
</br>

<h2>Add a Comment</h2>
<%= render 'comments/form' %>
<div class = "link">
    <%= link_to 'Back To Recipe Book', articles_path %>
</div>

Recipes/app/views/comments/_comment.html.erb
<p>
    <h4>Author Name:</h4>
    <text><%= comment.commenter %></text>
</p>
<p>
    <h4>Comment:</h4>
    <text><%= comment.body %></text>
</p>

<h4>
    <%= link_to 'Destroy Comment', [comment.article, comment],
                method: :delete,
                data: {confirm: 'Are you sure?'} %>
</h4>

Recipes/app/views/comments/_form.html.erb
<div class = "comment">
  <%= form_for([@article, @article.comments.build]) do |f| %>
    <h4>
      <%= f.label :Author_Name %><br>
      <%= f.text_field :commenter %>
    </h4>
    <h4>
      <%= f.label :Comment %><br>
      <%= f.text_area :body %>
    </h4>
    <p>
      <%= f.submit 'Save Comment' %>
    </p>
  <% end %>
</div>

Recipes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GOOD EATS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Recipes/app/views/recipe/recipe1.html.erb
<p>
    <h2>Recipe Name:</h2>
    </br>
    Shepherd's Pie
    
</p>

<p>
    <h2>Ingredients and Supplies:</h2>
    </br>
    1 1/2 pounds russet potatoes
</br>
    1/4 cup half-and-half
</br>
    2 ounces unsalted butter
</br>
    3/4 teaspoon kosher salt
</br>
    1/4 teaspoon freshly ground black pepper
</br>
    1 egg yolk
</br>
    2 tablespoons canola oil
</br>
    1 cup chopped onion
</br>
    2 carrots, peeled and diced small
</br>
    2 cloves garlic, minced
</br>
    1 1/2 pounds ground lamb
</br>
    1 teaspoon kosher salt
</br>
    1/2 teaspoon freshly ground black pepper
</br>
    2 tablespoons all-purpose flour
</br>
    2 teaspoons tomato paste
</br>
    1 cup chicken broth
</br>
    1 teaspoon Worcestershire sauce
</br>
    2 teaspoons freshly chopped rosemary leaves
</br>
    1 teaspoon freshly chopped thyme leaves
</br>
    1/2 cup fresh or frozen corn kernels
</br>
    1/2 cup fresh or frozen English peas
</p>

<p>
    <h2>Directions:</h2>
    </br>
    Step 1: Peel the potatoes and cut into 1/2-inch dice. Place in a medium saucepan and cover with cold water. Set over high heat, cover and bring to a boil. Once boiling, uncover, decrease the heat to maintain a simmer and cook until tender and easily crushed with tongs, approximately 10 to 15 minutes. Place the half-and-half and butter into a microwave-safe container and heat in the microwave until warmed through, about 35 seconds. Drain the potatoes in a colander and then return to the saucepan. Mash the potatoes and then add the half and half, butter, salt and pepper and continue to mash until smooth. Stir in the yolk until well combined.
    </br>
    </br>
    Step 2: Preheat the oven to 400 degrees F.
    </br>
    </br>
    Step 3: While the potatoes are cooking, prepare the filling. Place the canola oil into a 12-inch saute pan and set over medium high heat. Once the oil shimmers, add the onion and carrots and saute just until they begin to take on color, approximately 3 to 4 minutes. Add the garlic and stir to combine. Add the lamb, salt and pepper and cook until browned and cooked through, approximately 3 minutes. Sprinkle the meat with the flour and toss to coat, continuing to cook for another minute. Add the tomato paste, chicken broth, Worcestershire, rosemary, thyme, and stir to combine. Bring to a boil, reduce the heat to low, cover and simmer slowly 10 to 12 minutes or until the sauce is thickened slightly.
    </br>
    </br>
    Step 4:Add the corn and peas to the lamb mixture and spread evenly into an 11 by 7-inch glass baking dish. Top with the mashed potatoes, starting around the edges to create a seal to prevent the mixture from bubbling up and smooth with a rubber spatula. Place on a parchment lined half sheet pan on the middle rack of the oven and bake for 25 minutes or just until the potatoes begin to brown. Remove to a cooling rack for at least 15 minutes before serving.

</p>

</br>
 <%= link_to 'To Recipe Book', articles_path %>
 </br>
 <%= link_to 'Back to Main Page', welcome_index_path %>

Recipes/app/views/recipe2/recipe2.html.erb
<p>
    <h2>Recipe Name:</h2>
    </br>
    Shepherd's Pie
    
</p>

<p>
    <h2>Ingredients and Supplies:</h2>
    </br>
    3 cups all-purpose flour
</br>
1 teaspoon salt
</br>
3/4 cup vegetable shortening or lard
</br>
3/4 cup salted butter, cut into pieces
</br>
1 egg, lightly beaten
</br>
1 tablespoon distilled white vinegar
</br>
1 cup granulated sugar
</br>
3 tablespoons brown sugar
</br>
1/2 teaspoons salt
</br>
1 cup corn syrup (light or dark)
</br>
1/3 cup melted salted butter
</br>
1 teaspoon vanilla
</br>
3 whole eggs beaten
</br>
1 cup (heaping) chopped pecans
</p>

<p>
    <h2>Directions:</h2>
    </br>
    Step 1: Peel the potatoes and cut into 1/2-inch dice. Place in a medium saucepan and cover with cold water. Set over high heat, cover and bring to a boil. Once boiling, uncover, decrease the heat to maintain a simmer and cook until tender and easily crushed with tongs, approximately 10 to 15 minutes. Place the half-and-half and butter into a microwave-safe container and heat in the microwave until warmed through, about 35 seconds. Drain the potatoes in a colander and then return to the saucepan. Mash the potatoes and then add the half and half, butter, salt and pepper and continue to mash until smooth. Stir in the yolk until well combined.
    </br>
    </br>
    Step 2: Preheat the oven to 400 degrees F.
    </br>
    </br>
    Step 3: While the potatoes are cooking, prepare the filling. Place the canola oil into a 12-inch saute pan and set over medium high heat. Once the oil shimmers, add the onion and carrots and saute just until they begin to take on color, approximately 3 to 4 minutes. Add the garlic and stir to combine. Add the lamb, salt and pepper and cook until browned and cooked through, approximately 3 minutes. Sprinkle the meat with the flour and toss to coat, continuing to cook for another minute. Add the tomato paste, chicken broth, Worcestershire, rosemary, thyme, and stir to combine. Bring to a boil, reduce the heat to low, cover and simmer slowly 10 to 12 minutes or until the sauce is thickened slightly.
    </br>
    </br>
    Step 4: Add the corn and peas to the lamb mixture and spread evenly into an 11 by 7-inch glass baking dish. Top with the mashed potatoes, starting around the edges to create a seal to prevent the mixture from bubbling up and smooth with a rubber spatula. Place on a parchment lined half sheet pan on the middle rack of the oven and bake for 25 minutes or just until the potatoes begin to brown. Remove to a cooling rack for at least 15 minutes before serving.
    </br>
    </br>
    Step 5: Bake the pie for 30 minutes. Remove the foil, and then continue baking for 20 minutes, being careful not to burn the crust or pecans. The pie should not be overly jiggly when you remove it from the oven (though it will jiggle a bit). If it shakes a lot, cover with foil and bake for an additional 20 minute or until set. Required baking time seems to vary widely with this recipe. Sometimes it takes 50 minutes, sometimes it takes 75!
    </br>
    </br>
    Step 6: Allow to cool for several hours or overnight. Serve in thin slivers.
</p>

</br>
 <%= link_to 'To Recipe Book', articles_path %>
 </br>
 <%= link_to 'Back to Main Page', welcome_index_path %>

Recipes/app/views/recipe3/recipe3.html.erb
<p>
    <h2>Recipe Name:</h2>
    </br>
    Blueberry Scones with Lemon Glaze
</p>

<p>
    <h2>Ingredients and Supplies:</h2>
    </br>
    2 cups all-purpose flour
</br>
1 tablespoon baking powder
</br>
1/2 teaspoon salt
</br>
2 tablespoons sugar
</br>
5 tablespoons unsalted butter, cold, cut in chunks
</br>
1 cup fresh blueberries
</br>
1 cup heavy cream, plus more for brushing the scones
</br>
1/2 cup freshly squeezed lemon juice
</br>
2 cups confectioners' sugar, sifted
</br>
1 tablespoon unsalted butter
</br>
1 lemon, zest finely grated
</p>

<p>
    <h2>Directions:</h2>
    </br>
    Step 1: Preheat the oven to 400 degrees F.
    </br>
    </br>
    Step 2: Sift together the dry ingredients; the flour, baking powder, salt, and sugar. Using 2 forks or a pastry blender, cut in the butter to coat the pieces with the flour. The mixture should look like coarse crumbs. Fold the blueberries into the batter. Take care not to mash or bruise the blueberries because their strong color will bleed into the dough. Make a well in the center and pour in the heavy cream. Fold everything together just to incorporate; do not overwork the dough.
    </br>
    </br>
    Step 3: Press the dough out on a lightly floured surface into a rectangle about 12 by 3 by 1 1/4 inches. Cut the rectangle in 1/2 then cut the pieces in 1/2 again, giving you 4 (3-inch) squares. Cut the squares in 1/2 on a diagonal to give you the classic triangle shape. Place the scones on an ungreased cookie sheet and brush the tops with a little heavy cream. Bake for 15 to 20 minutes until beautiful and brown. Let the scones cool a bit before you apply the glaze.
    </br>
    </br>
    Step 4: You can make the lemon glaze in a double boiler, or for a simpler alternative, you can zap it in the microwave. Mix the lemon juice with the confectioners' until dissolved in a heatproof bowl over a pot of simmering water for the double-boiler method, or in a microwave-safe bowl. Whisk in the butter and lemon zest. Either nuke the glaze for 30 seconds or continue whisking in the double boiler. Whisk the glaze to smooth out any lumps, then drizzle the glaze over the top of the scones. Let it set a minute before serving.
</p>

</br>
 <%= link_to 'To Recipe Book', articles_path %>
 </br>
 <%= link_to 'Back to Main Page', welcome_index_path %>

Recipes/app/views/welcome/index.html.erb
<html>
    <head>
       <h1>
            <span><b>Good Eats</b>
            </br>
            Your Online Personal Cookbook</span>
        </h1>
         
    </head>
    <body>
        <div class = "food_image"> <%= image_tag("food.jpg")%> </div>
        <div id="wrap">
            <div class = "left">
                    <h2 class = "left_h2">Our Goal</h2>
                    <p class = "border">
                    Our goal is to create a personal online recipe cookbook for you, yes You!. 
                    It will allow you chefs out there to  add 
                    recipes to your very own cookbook. Being able to prepare your own meal 
                    is a mark of independence, maturity and financial stability. So get out there
                    and populate your cookbook with meals of your very own.
                    We also have some of our favorite recipes yet simple for you to benchmark your 
                    abilities in the kitchen.
                    Happy Cooking :)
                    </p>
                    
                <h2>Want to view some delicious recipes?</h2>
                <table class="rTable">
                    <thead>
                        <tr>
                            <th>Some of our Favorites</th>
                        </tr>
                    </thead>
                    
                    <tbody>
                        <tr>
                            <td><%= link_to 'Shepherds Pie', recipe_recipe1_path %></td>
                        </tr>
                        <tr>
                            <td><%= link_to 'Pecan Pie', recipe2_recipe2_path %></td>
                        </tr>
                        <tr>
                            <td><%= link_to 'Blueberry Scones with Lemon Glaze', recipe3_recipe3_path %></td>
                        </tr>
                        <tr>
                            <td><%= link_to 'Want to view more Recipes?', controller: 'articles' %></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
            <div class = "right">
                 <h2>
                     Want to add your own Recipe?
                </h2>
                 <%= image_tag("burrito-chicken-close-up-461198.jpg")%>
                 <br>
                 <%= link_to 'Create A New Recipe', new_article_path %>
            </div>
        </div>
 </body>
</html>